name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: Setup Node
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install Bun
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun dependencies
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: bun ci

      - name: Build project
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: bun run build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
