name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install Bun
        if: ${{ steps.release.outputs.release_published == 'true' }}
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_published == 'true' }}
        run: bun install

      - name: Build project
        if: ${{ steps.release.outputs.release_published == 'true' }}
        run: bun run build

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_published == 'true' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
